# Generated by Django 6.1 on 2026-09-13 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_experience_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='company',
            new_name='organization',
        ),
    ]
