# Generated by Django 6.1 on 2026-09-13 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_company_experience_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='ended_at',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='started_at',
            new_name='start_date',
        ),
    ]
