# Generated by Django 6.1 on 2026-09-13 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='title',
        ),
    ]
